source 'https://rubygems.org'

gem 'langchainrb'
gem 'ollama-ai'
gem 'faraday'
gem 'cli-ui'
gem 'ruby-openai'
gem 'anthropic'
gem 'raix', '~> 0.4.8'
gem 'mistral-ai'
gem 'xgb'
gem 'tensorflow'
gem 'disco'
gem 'libmf'
gem 'ngt'
gem 'xlearn'
gem 'parallel'
gem 'rumale'
gem 'onnxruntime'
gem 'omniai'
gem 'omniai-anthropic'
gem 'omniai-deepseek'
gem 'omniai-mistral'
gem 'omniai-google'
gem 'omniai-openai'
gem 'ruby_llm'
gem 'mpc'

# gem 'torch-rb'
# gem 'rumale-torch'
# gem 'instruct', github: 'instruct-rb/instruct', branch: 'development'
# gem 'attributed-string', github: 'instruct-rb/attributed-string', branch: 'main'
